//*
// Arke message broker proxy messages.
//
// This file outlines the gRPC interface for the Arke proxy.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: arke.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Producer_Connect_FullMethodName    = "/arke.Producer/Connect"
	Producer_Publish_FullMethodName    = "/arke.Producer/Publish"
	Producer_PublishOne_FullMethodName = "/arke.Producer/PublishOne"
	Producer_Disconnect_FullMethodName = "/arke.Producer/Disconnect"
)

// ProducerClient is the client API for Producer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for producing messages
type ProducerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Send a stream of messages to the message broker.
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, MessageResponse], error)
	// Send one message to the message broker.
	PublishOne(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type producerClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerClient(cc grpc.ClientConnInterface) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, Producer_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, MessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Producer_ServiceDesc.Streams[0], Producer_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, MessageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Producer_PublishClient = grpc.BidiStreamingClient[Message, MessageResponse]

func (c *producerClient) PublishOne(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, Producer_PublishOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Producer_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServer is the server API for Producer service.
// All implementations must embed UnimplementedProducerServer
// for forward compatibility.
//
// Service for producing messages
type ProducerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Send a stream of messages to the message broker.
	Publish(grpc.BidiStreamingServer[Message, MessageResponse]) error
	// Send one message to the message broker.
	PublishOne(context.Context, *Message) (*MessageResponse, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedProducerServer()
}

// UnimplementedProducerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProducerServer struct{}

func (UnimplementedProducerServer) Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProducerServer) Publish(grpc.BidiStreamingServer[Message, MessageResponse]) error {
	return status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedProducerServer) PublishOne(context.Context, *Message) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishOne not implemented")
}
func (UnimplementedProducerServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedProducerServer) mustEmbedUnimplementedProducerServer() {}
func (UnimplementedProducerServer) testEmbeddedByValue()                  {}

// UnsafeProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServer will
// result in compilation errors.
type UnsafeProducerServer interface {
	mustEmbedUnimplementedProducerServer()
}

func RegisterProducerServer(s grpc.ServiceRegistrar, srv ProducerServer) {
	// If the following call panics, it indicates UnimplementedProducerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Producer_ServiceDesc, srv)
}

func _Producer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Producer_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServer).Publish(&grpc.GenericServerStream[Message, MessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Producer_PublishServer = grpc.BidiStreamingServer[Message, MessageResponse]

func _Producer_PublishOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).PublishOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Producer_PublishOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).PublishOne(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Producer_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Producer_ServiceDesc is the grpc.ServiceDesc for Producer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Producer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Producer_Connect_Handler,
		},
		{
			MethodName: "PublishOne",
			Handler:    _Producer_PublishOne_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Producer_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Producer_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}

const (
	Consumer_Connect_FullMethodName          = "/arke.Consumer/Connect"
	Consumer_Consume_FullMethodName          = "/arke.Consumer/Consume"
	Consumer_Disconnect_FullMethodName       = "/arke.Consumer/Disconnect"
	Consumer_SourceStats_FullMethodName      = "/arke.Consumer/SourceStats"
	Consumer_SourceStatsGroup_FullMethodName = "/arke.Consumer/SourceStatsGroup"
)

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for consuming messages
type ConsumerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Consume, ConsumeResponse], error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Ask for and receive information about an arke.Source
	SourceStats(ctx context.Context, in *Source, opts ...grpc.CallOption) (*SourceStats, error)
	// Ask for and receive information about a group of arke.Sources
	SourceStatsGroup(ctx context.Context, in *Sources, opts ...grpc.CallOption) (*SourceStatsCollection, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, Consumer_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Consume, ConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Consumer_ServiceDesc.Streams[0], Consumer_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Consume, ConsumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consumer_ConsumeClient = grpc.BidiStreamingClient[Consume, ConsumeResponse]

func (c *consumerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Consumer_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) SourceStats(ctx context.Context, in *Source, opts ...grpc.CallOption) (*SourceStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceStats)
	err := c.cc.Invoke(ctx, Consumer_SourceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) SourceStatsGroup(ctx context.Context, in *Sources, opts ...grpc.CallOption) (*SourceStatsCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SourceStatsCollection)
	err := c.cc.Invoke(ctx, Consumer_SourceStatsGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
// All implementations must embed UnimplementedConsumerServer
// for forward compatibility.
//
// Service for consuming messages
type ConsumerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Consume(grpc.BidiStreamingServer[Consume, ConsumeResponse]) error
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
	// Ask for and receive information about an arke.Source
	SourceStats(context.Context, *Source) (*SourceStats, error)
	// Ask for and receive information about a group of arke.Sources
	SourceStatsGroup(context.Context, *Sources) (*SourceStatsCollection, error)
	mustEmbedUnimplementedConsumerServer()
}

// UnimplementedConsumerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServer struct{}

func (UnimplementedConsumerServer) Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConsumerServer) Consume(grpc.BidiStreamingServer[Consume, ConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedConsumerServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedConsumerServer) SourceStats(context.Context, *Source) (*SourceStats, error) {
	return nil, status.Error(codes.Unimplemented, "method SourceStats not implemented")
}
func (UnimplementedConsumerServer) SourceStatsGroup(context.Context, *Sources) (*SourceStatsCollection, error) {
	return nil, status.Error(codes.Unimplemented, "method SourceStatsGroup not implemented")
}
func (UnimplementedConsumerServer) mustEmbedUnimplementedConsumerServer() {}
func (UnimplementedConsumerServer) testEmbeddedByValue()                  {}

// UnsafeConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServer will
// result in compilation errors.
type UnsafeConsumerServer interface {
	mustEmbedUnimplementedConsumerServer()
}

func RegisterConsumerServer(s grpc.ServiceRegistrar, srv ConsumerServer) {
	// If the following call panics, it indicates UnimplementedConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Consumer_ServiceDesc, srv)
}

func _Consumer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsumerServer).Consume(&grpc.GenericServerStream[Consume, ConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Consumer_ConsumeServer = grpc.BidiStreamingServer[Consume, ConsumeResponse]

func _Consumer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_SourceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Source)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).SourceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_SourceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).SourceStats(ctx, req.(*Source))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_SourceStatsGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sources)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).SourceStatsGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Consumer_SourceStatsGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).SourceStatsGroup(ctx, req.(*Sources))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumer_ServiceDesc is the grpc.ServiceDesc for Consumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Consumer_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Consumer_Disconnect_Handler,
		},
		{
			MethodName: "SourceStats",
			Handler:    _Consumer_SourceStats_Handler,
		},
		{
			MethodName: "SourceStatsGroup",
			Handler:    _Consumer_SourceStatsGroup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _Consumer_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}

const (
	Healthz_Check_FullMethodName = "/arke.Healthz/Check"
)

// HealthzClient is the client API for Healthz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Service for health checks and communication
type HealthzClient interface {
	Check(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Health, Health], error)
}

type healthzClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthzClient(cc grpc.ClientConnInterface) HealthzClient {
	return &healthzClient{cc}
}

func (c *healthzClient) Check(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Health, Health], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Healthz_ServiceDesc.Streams[0], Healthz_Check_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Health, Health]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Healthz_CheckClient = grpc.BidiStreamingClient[Health, Health]

// HealthzServer is the server API for Healthz service.
// All implementations must embed UnimplementedHealthzServer
// for forward compatibility.
//
// *
// Service for health checks and communication
type HealthzServer interface {
	Check(grpc.BidiStreamingServer[Health, Health]) error
	mustEmbedUnimplementedHealthzServer()
}

// UnimplementedHealthzServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthzServer struct{}

func (UnimplementedHealthzServer) Check(grpc.BidiStreamingServer[Health, Health]) error {
	return status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthzServer) mustEmbedUnimplementedHealthzServer() {}
func (UnimplementedHealthzServer) testEmbeddedByValue()                 {}

// UnsafeHealthzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthzServer will
// result in compilation errors.
type UnsafeHealthzServer interface {
	mustEmbedUnimplementedHealthzServer()
}

func RegisterHealthzServer(s grpc.ServiceRegistrar, srv HealthzServer) {
	// If the following call panics, it indicates UnimplementedHealthzServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Healthz_ServiceDesc, srv)
}

func _Healthz_Check_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthzServer).Check(&grpc.GenericServerStream[Health, Health]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Healthz_CheckServer = grpc.BidiStreamingServer[Health, Health]

// Healthz_ServiceDesc is the grpc.ServiceDesc for Healthz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Healthz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Healthz",
	HandlerType: (*HealthzServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Check",
			Handler:       _Healthz_Check_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}
