//*
// Arke message broker proxy messages.
//
// This file outlines the gRPC interface for the Arke proxy.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: arke.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address_TargetType int32

const (
	Address_TOPIC  Address_TargetType = 0 // The address is a message topic.
	Address_QUEUE  Address_TargetType = 1 // The address is a message queue.
	Address_FILTER Address_TargetType = 2 // The address is a filtered queue.
	Address_STREAM Address_TargetType = 3 // The address is a stream.
)

// Enum value maps for Address_TargetType.
var (
	Address_TargetType_name = map[int32]string{
		0: "TOPIC",
		1: "QUEUE",
		2: "FILTER",
		3: "STREAM",
	}
	Address_TargetType_value = map[string]int32{
		"TOPIC":  0,
		"QUEUE":  1,
		"FILTER": 2,
		"STREAM": 3,
	}
)

func (x Address_TargetType) Enum() *Address_TargetType {
	p := new(Address_TargetType)
	*p = x
	return p
}

func (x Address_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Address_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_arke_proto_enumTypes[0].Descriptor()
}

func (Address_TargetType) Type() protoreflect.EnumType {
	return &file_arke_proto_enumTypes[0]
}

func (x Address_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Address_TargetType.Descriptor instead.
func (Address_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{5, 0}
}

type Source_TargetType int32

const (
	Source_QUEUE     Source_TargetType = 0 // The Source is a HA queue
	Source_TEMPORARY Source_TargetType = 1 // The Source is a temporary queue
	Source_STREAM    Source_TargetType = 2 // The Source is a stream
)

// Enum value maps for Source_TargetType.
var (
	Source_TargetType_name = map[int32]string{
		0: "QUEUE",
		1: "TEMPORARY",
		2: "STREAM",
	}
	Source_TargetType_value = map[string]int32{
		"QUEUE":     0,
		"TEMPORARY": 1,
		"STREAM":    2,
	}
)

func (x Source_TargetType) Enum() *Source_TargetType {
	p := new(Source_TargetType)
	*p = x
	return p
}

func (x Source_TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source_TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_arke_proto_enumTypes[1].Descriptor()
}

func (Source_TargetType) Type() protoreflect.EnumType {
	return &file_arke_proto_enumTypes[1]
}

func (x Source_TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source_TargetType.Descriptor instead.
func (Source_TargetType) EnumDescriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{6, 0}
}

type Filter_MatchType int32

const (
	Filter_ALL Filter_MatchType = 0 // All matches must match for a successful filter.
	Filter_ANY Filter_MatchType = 1 // Any match can match for a successful filter.
)

// Enum value maps for Filter_MatchType.
var (
	Filter_MatchType_name = map[int32]string{
		0: "ALL",
		1: "ANY",
	}
	Filter_MatchType_value = map[string]int32{
		"ALL": 0,
		"ANY": 1,
	}
)

func (x Filter_MatchType) Enum() *Filter_MatchType {
	p := new(Filter_MatchType)
	*p = x
	return p
}

func (x Filter_MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter_MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_arke_proto_enumTypes[2].Descriptor()
}

func (Filter_MatchType) Type() protoreflect.EnumType {
	return &file_arke_proto_enumTypes[2]
}

func (x Filter_MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter_MatchType.Descriptor instead.
func (Filter_MatchType) EnumDescriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{7, 0}
}

type HealthStatus_Code int32

const (
	HealthStatus_OK        HealthStatus_Code = 0 // Everything is fine.
	HealthStatus_UNHEALTHY HealthStatus_Code = 1 // Everything is not fine (cpu/memory high) but we are operational.
	HealthStatus_GOAWAY    HealthStatus_Code = 2 // Please go away and come back.
)

// Enum value maps for HealthStatus_Code.
var (
	HealthStatus_Code_name = map[int32]string{
		0: "OK",
		1: "UNHEALTHY",
		2: "GOAWAY",
	}
	HealthStatus_Code_value = map[string]int32{
		"OK":        0,
		"UNHEALTHY": 1,
		"GOAWAY":    2,
	}
)

func (x HealthStatus_Code) Enum() *HealthStatus_Code {
	p := new(HealthStatus_Code)
	*p = x
	return p
}

func (x HealthStatus_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_arke_proto_enumTypes[3].Descriptor()
}

func (HealthStatus_Code) Type() protoreflect.EnumType {
	return &file_arke_proto_enumTypes[3]
}

func (x HealthStatus_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus_Code.Descriptor instead.
func (HealthStatus_Code) EnumDescriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{20, 0}
}

// *
// Represents the broker connection information. This is passed
// in by the client allowing us to remain a proxy, but also
// allowing us to support multiple providers at once such as
// RabbitMQ and Kafka.
type ConnectionConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                        // Broker hostname or IP address.
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                       // Broker port.
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                                // Provider type, currently only amqp091.
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`                                    // Tenant name for this connection. Tenant is not required
	Credentials   *Credentials           `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`                          // Authentication credentials.
	CaCertificate []byte                 `protobuf:"bytes,7,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"` // TLS Certificate authority for broker. Implies tls.
	Tls           bool                   `protobuf:"varint,8,opt,name=tls,proto3" json:"tls,omitempty"`                                         // Should this provider connection use TLS. If used in conjunction with CaCertificate, the certificate will be used for verification. If no CaCertificate is provided then the providers certificate must be trusted by the system certificates.
	ClientName    string                 `protobuf:"bytes,9,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`          // The name of the client connecting.
	AdminPort     int32                  `protobuf:"varint,10,opt,name=admin_port,json=adminPort,proto3" json:"admin_port,omitempty"`           // The administrative port for the provider (eg. RabbitMQ management port) for any actions needing to be performed by the provider (eg. modifying bindings for RabbitMQ)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionConfiguration) Reset() {
	*x = ConnectionConfiguration{}
	mi := &file_arke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionConfiguration) ProtoMessage() {}

func (x *ConnectionConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionConfiguration.ProtoReflect.Descriptor instead.
func (*ConnectionConfiguration) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionConfiguration) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionConfiguration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionConfiguration) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ConnectionConfiguration) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConnectionConfiguration) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ConnectionConfiguration) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *ConnectionConfiguration) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *ConnectionConfiguration) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ConnectionConfiguration) GetAdminPort() int32 {
	if x != nil {
		return x.AdminPort
	}
	return 0
}

// *
// Represents the broker authentication information.
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // Username for authenticating to broker.
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Password for authenticating to broker.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_arke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// *
// Represents the connection response
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates whether the connection was successful.
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error if the connection failed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_arke_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Represents a message that is being produced or consumed. The
// error property is set by the proxy when an error occurs during
// the consumer process.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                                                 // The proxy sets this UUID when the message is consumed. It should be returned when a message is Ack/Nack'ed.
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // The message headers.
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                                                                 // The message body.
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                                                                           // The distination for a published message.
	Persistent    bool                   `protobuf:"varint,5,opt,name=persistent,proto3" json:"persistent,omitempty"`                                                                    // Indicates whether to persist the message.
	Error         *Error                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                                                               // Error message if consuming failed.
	Confirm       bool                   `protobuf:"varint,7,opt,name=confirm,proto3" json:"confirm,omitempty"`                                                                          // Enables guaranteed delivery to the broker.
	PublishId     int64                  `protobuf:"varint,8,opt,name=publish_id,json=publishId,proto3" json:"publish_id,omitempty"`                                                     // Combined with the publisher_name to provide publishing deduplication. The publish_id is a strictly increasing sequence.
	PublisherName string                 `protobuf:"bytes,11,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`                                         // The publisher_name is used in conjunction with publish_id to provide message deduplication on Streams ONLY.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_arke_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Message) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

func (x *Message) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Message) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *Message) GetPublishId() int64 {
	if x != nil {
		return x.PublishId
	}
	return 0
}

func (x *Message) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

// *
// Represents the response from publishing a message.
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Indicates whether the message was published successfully.
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error if publishing failed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_arke_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{4}
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Represents the publishing destination for a message.
type Address struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // The name of this destination address.
	Subjects []string               `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`                       // The subjects of the address. Multiple subjects are allowed on Subscribe, but not on Publish.
	Type     Address_TargetType     `protobuf:"varint,3,opt,name=type,proto3,enum=arke.Address_TargetType" json:"type,omitempty"` // Target type, default is TOPIC.
	// Deprecated: Marked as deprecated in arke.proto.
	Durable       bool     `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete    bool     `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`         // Should the address automatically delete.
	ParentAddress *Address `protobuf:"bytes,6,opt,name=parent_address,json=parentAddress,proto3" json:"parent_address,omitempty"` // A parent Address. Usage includes Address to Address binding.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_arke_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{5}
}

func (x *Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Address) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Address) GetType() Address_TargetType {
	if x != nil {
		return x.Type
	}
	return Address_TOPIC
}

// Deprecated: Marked as deprecated in arke.proto.
func (x *Address) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *Address) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *Address) GetParentAddress() *Address {
	if x != nil {
		return x.ParentAddress
	}
	return nil
}

// *
// Represents the source for consumer subscriptions. The Stream TargetType
// does not support exclusive or auto_delete. Streams also do not support the
// following Options: Exclusive, DeadLetterAdress or DeadLetterSubject.
type Source struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // The name of this source.
	Address *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // The Address associated with this source.
	// Deprecated: Marked as deprecated in arke.proto.
	Durable              bool              `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete           bool              `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`                                                  // Should this Source automatically delete.
	Options              map[string]string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional options for this Source. Option keys include: MessageTTL, Expires, DeadLetterAddress, DeadLetterSubject, Offset(Valid values: first, continue, next, or a quoted integer), ConsumerGroup.
	Exclusive            bool              `protobuf:"varint,8,opt,name=exclusive,proto3" json:"exclusive,omitempty"`                                                                      // Should this source be exclusive to the subscriber.
	PrefetchCount        int32             `protobuf:"varint,9,opt,name=prefetch_count,json=prefetchCount,proto3" json:"prefetch_count,omitempty"`                                         // Set the prefetch count for this subscriber. Must be greater than 0. Defaults to 1.
	Filters              []*Filter         `protobuf:"bytes,10,rep,name=filters,proto3" json:"filters,omitempty"`                                                                          // Filters for this Source.
	Type                 Source_TargetType `protobuf:"varint,11,opt,name=type,proto3,enum=arke.Source_TargetType" json:"type,omitempty"`                                                   // Target type, default is QUEUE.
	DeclareOnly          bool              `protobuf:"varint,12,opt,name=declare_only,json=declareOnly,proto3" json:"declare_only,omitempty"`                                              // Declare the source and any bindings but do not actually consume any messages.
	SingleActiveConsumer bool              `protobuf:"varint,13,opt,name=single_active_consumer,json=singleActiveConsumer,proto3" json:"single_active_consumer,omitempty"`                 // Only one consumer should be allowed to subscribe to this source. For queues, this applies to all consumers on the queue. For streams this option must be paired with the ConsumerGroup option.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_arke_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{6}
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Deprecated: Marked as deprecated in arke.proto.
func (x *Source) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *Source) GetAutoDelete() bool {
	if x != nil {
		return x.AutoDelete
	}
	return false
}

func (x *Source) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Source) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *Source) GetPrefetchCount() int32 {
	if x != nil {
		return x.PrefetchCount
	}
	return 0
}

func (x *Source) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Source) GetType() Source_TargetType {
	if x != nil {
		return x.Type
	}
	return Source_QUEUE
}

func (x *Source) GetDeclareOnly() bool {
	if x != nil {
		return x.DeclareOnly
	}
	return false
}

func (x *Source) GetSingleActiveConsumer() bool {
	if x != nil {
		return x.SingleActiveConsumer
	}
	return false
}

// *
// Represents a filter for Message.headers. The Filter will prevent a consumer
// from consuming all messages from a Source.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`                       // One or more filter Matches.
	Type          Filter_MatchType       `protobuf:"varint,2,opt,name=type,proto3,enum=arke.Filter_MatchType" json:"type,omitempty"` // The MatchType for this filter. Default is ALL.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_arke_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{7}
}

func (x *Filter) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *Filter) GetType() Filter_MatchType {
	if x != nil {
		return x.Type
	}
	return Filter_ALL
}

// *
// Represents the key/value match for Message.headers. Currently only an
// exact match is supported.
type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // The Message.headers key
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The Message.headers value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_arke_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{8}
}

func (x *Match) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Match) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// *
// No parameters or return value.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_arke_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{9}
}

// *
// Represents a generic error message.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                 // The text error message.
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                      // The error code.
	IsFatal       bool                   `protobuf:"varint,3,opt,name=is_fatal,json=isFatal,proto3" json:"is_fatal,omitempty"` // Indicator that a fatal error has occured, and a reconnect is required on this connection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_arke_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{10}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetIsFatal() bool {
	if x != nil {
		return x.IsFatal
	}
	return false
}

// *
// Message used to ack or nack a message UUID
type MessageConsumed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                      // arke.Message UUID returned from Consume.
	Nack          bool                   `protobuf:"varint,2,opt,name=nack,proto3" json:"nack,omitempty"`                                     // Nack (true) or Ack (false) the message. By default all messages will be Ack'd unless you set this to true.
	RequeueDelay  int32                  `protobuf:"varint,3,opt,name=requeue_delay,json=requeueDelay,proto3" json:"requeue_delay,omitempty"` // Requeue delay in seconds for Nack messages. Delay of zero will result in Nack'd messages getting dequeued. If delay is greater than zero, the message will be requeued after the delay.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageConsumed) Reset() {
	*x = MessageConsumed{}
	mi := &file_arke_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageConsumed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageConsumed) ProtoMessage() {}

func (x *MessageConsumed) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageConsumed.ProtoReflect.Descriptor instead.
func (*MessageConsumed) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{11}
}

func (x *MessageConsumed) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageConsumed) GetNack() bool {
	if x != nil {
		return x.Nack
	}
	return false
}

func (x *MessageConsumed) GetRequeueDelay() int32 {
	if x != nil {
		return x.RequeueDelay
	}
	return 0
}

// *
// Response to a MessageConsumed message
type MessageConsumedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`        // Message UUID of the arke.Message
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // Was the ack or nack successful.
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // Error if the MessageConsumed failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageConsumedResponse) Reset() {
	*x = MessageConsumedResponse{}
	mi := &file_arke_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageConsumedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageConsumedResponse) ProtoMessage() {}

func (x *MessageConsumedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageConsumedResponse.ProtoReflect.Descriptor instead.
func (*MessageConsumedResponse) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{12}
}

func (x *MessageConsumedResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MessageConsumedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageConsumedResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Sent on the Consume stream from the client to either start consuming messages or to ack/nack messages
type Consume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Consume_Src
	//	*Consume_Ack
	Msg           isConsume_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consume) Reset() {
	*x = Consume{}
	mi := &file_arke_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{13}
}

func (x *Consume) GetMsg() isConsume_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Consume) GetSrc() *Source {
	if x != nil {
		if x, ok := x.Msg.(*Consume_Src); ok {
			return x.Src
		}
	}
	return nil
}

func (x *Consume) GetAck() *MessageConsumed {
	if x != nil {
		if x, ok := x.Msg.(*Consume_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isConsume_Msg interface {
	isConsume_Msg()
}

type Consume_Src struct {
	Src *Source `protobuf:"bytes,1,opt,name=src,proto3,oneof"`
}

type Consume_Ack struct {
	Ack *MessageConsumed `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*Consume_Src) isConsume_Msg() {}

func (*Consume_Ack) isConsume_Msg() {}

// *
// Response to a Consume request where Source.DeclareOnly is true.
type DeclareOnlyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Was the source declaration successful.
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Error if the source declaration failed.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareOnlyResponse) Reset() {
	*x = DeclareOnlyResponse{}
	mi := &file_arke_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareOnlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareOnlyResponse) ProtoMessage() {}

func (x *DeclareOnlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareOnlyResponse.ProtoReflect.Descriptor instead.
func (*DeclareOnlyResponse) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{14}
}

func (x *DeclareOnlyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeclareOnlyResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// *
// Response to a Consume message. Either a Message or a MessageConsumedResponse
type ConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resp:
	//
	//	*ConsumeResponse_Msg
	//	*ConsumeResponse_ConsumedResponse
	//	*ConsumeResponse_Error
	//	*ConsumeResponse_DeclareOnlyResponse
	Resp          isConsumeResponse_Resp `protobuf_oneof:"resp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_arke_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{15}
}

func (x *ConsumeResponse) GetResp() isConsumeResponse_Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *ConsumeResponse) GetMsg() *Message {
	if x != nil {
		if x, ok := x.Resp.(*ConsumeResponse_Msg); ok {
			return x.Msg
		}
	}
	return nil
}

func (x *ConsumeResponse) GetConsumedResponse() *MessageConsumedResponse {
	if x != nil {
		if x, ok := x.Resp.(*ConsumeResponse_ConsumedResponse); ok {
			return x.ConsumedResponse
		}
	}
	return nil
}

func (x *ConsumeResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Resp.(*ConsumeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ConsumeResponse) GetDeclareOnlyResponse() *DeclareOnlyResponse {
	if x != nil {
		if x, ok := x.Resp.(*ConsumeResponse_DeclareOnlyResponse); ok {
			return x.DeclareOnlyResponse
		}
	}
	return nil
}

type isConsumeResponse_Resp interface {
	isConsumeResponse_Resp()
}

type ConsumeResponse_Msg struct {
	Msg *Message `protobuf:"bytes,1,opt,name=msg,proto3,oneof"`
}

type ConsumeResponse_ConsumedResponse struct {
	ConsumedResponse *MessageConsumedResponse `protobuf:"bytes,2,opt,name=consumed_response,json=consumedResponse,proto3,oneof"`
}

type ConsumeResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ConsumeResponse_DeclareOnlyResponse struct {
	DeclareOnlyResponse *DeclareOnlyResponse `protobuf:"bytes,4,opt,name=declare_only_response,json=declareOnlyResponse,proto3,oneof"`
}

func (*ConsumeResponse_Msg) isConsumeResponse_Resp() {}

func (*ConsumeResponse_ConsumedResponse) isConsumeResponse_Resp() {}

func (*ConsumeResponse_Error) isConsumeResponse_Resp() {}

func (*ConsumeResponse_DeclareOnlyResponse) isConsumeResponse_Resp() {}

// *
// SourceStats includes information about the source from the broker
type SourceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`                                       // Any error encountered while retrieving the SourceStats.
	MessageCount  int64                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`    // Total number of messages in the queue.
	ConsumerCount int32                  `protobuf:"varint,3,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"` // Number of consumers on the queue or stream.
	LastOffset    int64                  `protobuf:"varint,4,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`          // Offset of the last message in the stream.
	CurrentOffset int64                  `protobuf:"varint,5,opt,name=current_offset,json=currentOffset,proto3" json:"current_offset,omitempty"` // Current stream offset for the specified consumer.
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                                         // Name of the source.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStats) Reset() {
	*x = SourceStats{}
	mi := &file_arke_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStats) ProtoMessage() {}

func (x *SourceStats) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStats.ProtoReflect.Descriptor instead.
func (*SourceStats) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{16}
}

func (x *SourceStats) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SourceStats) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SourceStats) GetConsumerCount() int32 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *SourceStats) GetLastOffset() int64 {
	if x != nil {
		return x.LastOffset
	}
	return 0
}

func (x *SourceStats) GetCurrentOffset() int64 {
	if x != nil {
		return x.CurrentOffset
	}
	return 0
}

func (x *SourceStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
// Represents a group of Sources
type Sources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"` // The sources we want metrics returned for.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sources) Reset() {
	*x = Sources{}
	mi := &file_arke_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sources) ProtoMessage() {}

func (x *Sources) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sources.ProtoReflect.Descriptor instead.
func (*Sources) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{17}
}

func (x *Sources) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

// *
// Return a group of SourceStats for the specified Sources.
type SourceStatsCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Any error encountered while retrieving the SourcesMetrics
	Stats         []*SourceStats         `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"` // A list of SourceStats
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatsCollection) Reset() {
	*x = SourceStatsCollection{}
	mi := &file_arke_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatsCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatsCollection) ProtoMessage() {}

func (x *SourceStatsCollection) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatsCollection.ProtoReflect.Descriptor instead.
func (*SourceStatsCollection) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{18}
}

func (x *SourceStatsCollection) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SourceStatsCollection) GetStats() []*SourceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// *
// Message requesting the health of the other end of the stream. Essentially a ping.
type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID to identify the check and match with the response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_arke_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheck) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// *
// Message containing the response to a health check request
type HealthStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // UUID of the HealthCheck message being responded to
	Time               *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Code               HealthStatus_Code      `protobuf:"varint,3,opt,name=code,proto3,enum=arke.HealthStatus_Code" json:"code,omitempty"`
	CpuAvailability    float32                `protobuf:"fixed32,4,opt,name=cpu_availability,json=cpuAvailability,proto3" json:"cpu_availability,omitempty"`          // CPU availability as a ratio (0.0 to 1.0, -1 as unknown)
	MemoryAvailability float32                `protobuf:"fixed32,5,opt,name=memory_availability,json=memoryAvailability,proto3" json:"memory_availability,omitempty"` // Memory availability as a ratio (0.0 to 1.0, -1 as unknown)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_arke_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{20}
}

func (x *HealthStatus) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *HealthStatus) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HealthStatus) GetCode() HealthStatus_Code {
	if x != nil {
		return x.Code
	}
	return HealthStatus_OK
}

func (x *HealthStatus) GetCpuAvailability() float32 {
	if x != nil {
		return x.CpuAvailability
	}
	return 0
}

func (x *HealthStatus) GetMemoryAvailability() float32 {
	if x != nil {
		return x.MemoryAvailability
	}
	return 0
}

// *
// Message used to communicate or request health to/from the server and client
type Health struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resp:
	//
	//	*Health_Check
	//	*Health_Status
	Resp          isHealth_Resp `protobuf_oneof:"resp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_arke_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_arke_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_arke_proto_rawDescGZIP(), []int{21}
}

func (x *Health) GetResp() isHealth_Resp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *Health) GetCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Resp.(*Health_Check); ok {
			return x.Check
		}
	}
	return nil
}

func (x *Health) GetStatus() *HealthStatus {
	if x != nil {
		if x, ok := x.Resp.(*Health_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isHealth_Resp interface {
	isHealth_Resp()
}

type Health_Check struct {
	Check *HealthCheck `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
}

type Health_Status struct {
	Status *HealthStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*Health_Check) isHealth_Resp() {}

func (*Health_Status) isHealth_Resp() {}

var File_arke_proto protoreflect.FileDescriptor

const file_arke_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"arke.proto\x12\x04arke\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\x17ConnectionConfiguration\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x123\n" +
	"\vcredentials\x18\x05 \x01(\v2\x11.arke.CredentialsR\vcredentials\x12%\n" +
	"\x0eca_certificate\x18\a \x01(\fR\rcaCertificate\x12\x10\n" +
	"\x03tls\x18\b \x01(\bR\x03tls\x12\x1f\n" +
	"\vclient_name\x18\t \x01(\tR\n" +
	"clientName\x12\x1d\n" +
	"\n" +
	"admin_port\x18\n" +
	" \x01(\x05R\tadminPortJ\x04\b\x06\x10\aJ\x04\b\v\x10\fR\x0eprefetch_countR\x0epublisher_name\"E\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"N\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.arke.ErrorR\x05error\"\xef\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x124\n" +
	"\aheaders\x18\x02 \x03(\v2\x1a.arke.Message.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12'\n" +
	"\aaddress\x18\x04 \x01(\v2\r.arke.AddressR\aaddress\x12\x1e\n" +
	"\n" +
	"persistent\x18\x05 \x01(\bR\n" +
	"persistent\x12!\n" +
	"\x05error\x18\x06 \x01(\v2\v.arke.ErrorR\x05error\x12\x18\n" +
	"\aconfirm\x18\a \x01(\bR\aconfirm\x12\x1d\n" +
	"\n" +
	"publish_id\x18\b \x01(\x03R\tpublishId\x12%\n" +
	"\x0epublisher_name\x18\v \x01(\tR\rpublisherName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.arke.ErrorR\x05error\"\x98\x02\n" +
	"\aAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubjects\x18\x02 \x03(\tR\bsubjects\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.arke.Address.TargetTypeR\x04type\x12\x1c\n" +
	"\adurable\x18\x04 \x01(\bB\x02\x18\x01R\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x05 \x01(\bR\n" +
	"autoDelete\x124\n" +
	"\x0eparent_address\x18\x06 \x01(\v2\r.arke.AddressR\rparentAddress\":\n" +
	"\n" +
	"TargetType\x12\t\n" +
	"\x05TOPIC\x10\x00\x12\t\n" +
	"\x05QUEUE\x10\x01\x12\n" +
	"\n" +
	"\x06FILTER\x10\x02\x12\n" +
	"\n" +
	"\x06STREAM\x10\x03\"\xaa\x04\n" +
	"\x06Source\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\aaddress\x18\x03 \x01(\v2\r.arke.AddressR\aaddress\x12\x1c\n" +
	"\adurable\x18\x04 \x01(\bB\x02\x18\x01R\adurable\x12\x1f\n" +
	"\vauto_delete\x18\x05 \x01(\bR\n" +
	"autoDelete\x123\n" +
	"\aoptions\x18\a \x03(\v2\x19.arke.Source.OptionsEntryR\aoptions\x12\x1c\n" +
	"\texclusive\x18\b \x01(\bR\texclusive\x12%\n" +
	"\x0eprefetch_count\x18\t \x01(\x05R\rprefetchCount\x12&\n" +
	"\afilters\x18\n" +
	" \x03(\v2\f.arke.FilterR\afilters\x12+\n" +
	"\x04type\x18\v \x01(\x0e2\x17.arke.Source.TargetTypeR\x04type\x12!\n" +
	"\fdeclare_only\x18\f \x01(\bR\vdeclareOnly\x124\n" +
	"\x16single_active_consumer\x18\r \x01(\bR\x14singleActiveConsumer\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\n" +
	"TargetType\x12\t\n" +
	"\x05QUEUE\x10\x00\x12\r\n" +
	"\tTEMPORARY\x10\x01\x12\n" +
	"\n" +
	"\x06STREAM\x10\x02J\x04\b\x06\x10\aR\x06filter\"z\n" +
	"\x06Filter\x12%\n" +
	"\amatches\x18\x01 \x03(\v2\v.arke.MatchR\amatches\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.arke.Filter.MatchTypeR\x04type\"\x1d\n" +
	"\tMatchType\x12\a\n" +
	"\x03ALL\x10\x00\x12\a\n" +
	"\x03ANY\x10\x01\"1\n" +
	"\x05Match\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\a\n" +
	"\x05Empty\"P\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x19\n" +
	"\bis_fatal\x18\x03 \x01(\bR\aisFatal\"^\n" +
	"\x0fMessageConsumed\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04nack\x18\x02 \x01(\bR\x04nack\x12#\n" +
	"\rrequeue_delay\x18\x03 \x01(\x05R\frequeueDelay\"j\n" +
	"\x17MessageConsumedResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\x05error\x18\x03 \x01(\v2\v.arke.ErrorR\x05error\"]\n" +
	"\aConsume\x12 \n" +
	"\x03src\x18\x01 \x01(\v2\f.arke.SourceH\x00R\x03src\x12)\n" +
	"\x03ack\x18\x02 \x01(\v2\x15.arke.MessageConsumedH\x00R\x03ackB\x05\n" +
	"\x03msg\"R\n" +
	"\x13DeclareOnlyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.arke.ErrorR\x05error\"\x80\x02\n" +
	"\x0fConsumeResponse\x12!\n" +
	"\x03msg\x18\x01 \x01(\v2\r.arke.MessageH\x00R\x03msg\x12L\n" +
	"\x11consumed_response\x18\x02 \x01(\v2\x1d.arke.MessageConsumedResponseH\x00R\x10consumedResponse\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\v.arke.ErrorH\x00R\x05error\x12O\n" +
	"\x15declare_only_response\x18\x04 \x01(\v2\x19.arke.DeclareOnlyResponseH\x00R\x13declareOnlyResponseB\x06\n" +
	"\x04resp\"\xd8\x01\n" +
	"\vSourceStats\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\v.arke.ErrorR\x05error\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x03R\fmessageCount\x12%\n" +
	"\x0econsumer_count\x18\x03 \x01(\x05R\rconsumerCount\x12\x1f\n" +
	"\vlast_offset\x18\x04 \x01(\x03R\n" +
	"lastOffset\x12%\n" +
	"\x0ecurrent_offset\x18\x05 \x01(\x03R\rcurrentOffset\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"1\n" +
	"\aSources\x12&\n" +
	"\asources\x18\x01 \x03(\v2\f.arke.SourceR\asources\"c\n" +
	"\x15SourceStatsCollection\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\v.arke.ErrorR\x05error\x12'\n" +
	"\x05stats\x18\x02 \x03(\v2\x11.arke.SourceStatsR\x05stats\"!\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x86\x02\n" +
	"\fHealthStatus\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12+\n" +
	"\x04code\x18\x03 \x01(\x0e2\x17.arke.HealthStatus.CodeR\x04code\x12)\n" +
	"\x10cpu_availability\x18\x04 \x01(\x02R\x0fcpuAvailability\x12/\n" +
	"\x13memory_availability\x18\x05 \x01(\x02R\x12memoryAvailability\")\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tUNHEALTHY\x10\x01\x12\n" +
	"\n" +
	"\x06GOAWAY\x10\x02\"i\n" +
	"\x06Health\x12)\n" +
	"\x05check\x18\x01 \x01(\v2\x11.arke.HealthCheckH\x00R\x05check\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x12.arke.HealthStatusH\x00R\x06statusB\x06\n" +
	"\x04resp2\xe4\x01\n" +
	"\bProducer\x12A\n" +
	"\aConnect\x12\x1d.arke.ConnectionConfiguration\x1a\x15.arke.ConnectResponse\"\x00\x125\n" +
	"\aPublish\x12\r.arke.Message\x1a\x15.arke.MessageResponse\"\x00(\x010\x01\x124\n" +
	"\n" +
	"PublishOne\x12\r.arke.Message\x1a\x15.arke.MessageResponse\"\x00\x12(\n" +
	"\n" +
	"Disconnect\x12\v.arke.Empty\x1a\v.arke.Empty\"\x002\xa2\x02\n" +
	"\bConsumer\x12A\n" +
	"\aConnect\x12\x1d.arke.ConnectionConfiguration\x1a\x15.arke.ConnectResponse\"\x00\x125\n" +
	"\aConsume\x12\r.arke.Consume\x1a\x15.arke.ConsumeResponse\"\x00(\x010\x01\x12(\n" +
	"\n" +
	"Disconnect\x12\v.arke.Empty\x1a\v.arke.Empty\"\x00\x120\n" +
	"\vSourceStats\x12\f.arke.Source\x1a\x11.arke.SourceStats\"\x00\x12@\n" +
	"\x10SourceStatsGroup\x12\r.arke.Sources\x1a\x1b.arke.SourceStatsCollection\"\x0024\n" +
	"\aHealthz\x12)\n" +
	"\x05Check\x12\f.arke.Health\x1a\f.arke.Health\"\x00(\x010\x01B7\n" +
	"\borg.arkeB\n" +
	"ArkeProtosZ\x1fgithub.com/sassoftware/arke/apib\x06proto3"

var (
	file_arke_proto_rawDescOnce sync.Once
	file_arke_proto_rawDescData []byte
)

func file_arke_proto_rawDescGZIP() []byte {
	file_arke_proto_rawDescOnce.Do(func() {
		file_arke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arke_proto_rawDesc), len(file_arke_proto_rawDesc)))
	})
	return file_arke_proto_rawDescData
}

var file_arke_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_arke_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_arke_proto_goTypes = []any{
	(Address_TargetType)(0),         // 0: arke.Address.TargetType
	(Source_TargetType)(0),          // 1: arke.Source.TargetType
	(Filter_MatchType)(0),           // 2: arke.Filter.MatchType
	(HealthStatus_Code)(0),          // 3: arke.HealthStatus.Code
	(*ConnectionConfiguration)(nil), // 4: arke.ConnectionConfiguration
	(*Credentials)(nil),             // 5: arke.Credentials
	(*ConnectResponse)(nil),         // 6: arke.ConnectResponse
	(*Message)(nil),                 // 7: arke.Message
	(*MessageResponse)(nil),         // 8: arke.MessageResponse
	(*Address)(nil),                 // 9: arke.Address
	(*Source)(nil),                  // 10: arke.Source
	(*Filter)(nil),                  // 11: arke.Filter
	(*Match)(nil),                   // 12: arke.Match
	(*Empty)(nil),                   // 13: arke.Empty
	(*Error)(nil),                   // 14: arke.Error
	(*MessageConsumed)(nil),         // 15: arke.MessageConsumed
	(*MessageConsumedResponse)(nil), // 16: arke.MessageConsumedResponse
	(*Consume)(nil),                 // 17: arke.Consume
	(*DeclareOnlyResponse)(nil),     // 18: arke.DeclareOnlyResponse
	(*ConsumeResponse)(nil),         // 19: arke.ConsumeResponse
	(*SourceStats)(nil),             // 20: arke.SourceStats
	(*Sources)(nil),                 // 21: arke.Sources
	(*SourceStatsCollection)(nil),   // 22: arke.SourceStatsCollection
	(*HealthCheck)(nil),             // 23: arke.HealthCheck
	(*HealthStatus)(nil),            // 24: arke.HealthStatus
	(*Health)(nil),                  // 25: arke.Health
	nil,                             // 26: arke.Message.HeadersEntry
	nil,                             // 27: arke.Source.OptionsEntry
	(*timestamppb.Timestamp)(nil),   // 28: google.protobuf.Timestamp
}
var file_arke_proto_depIdxs = []int32{
	5,  // 0: arke.ConnectionConfiguration.credentials:type_name -> arke.Credentials
	14, // 1: arke.ConnectResponse.error:type_name -> arke.Error
	26, // 2: arke.Message.headers:type_name -> arke.Message.HeadersEntry
	9,  // 3: arke.Message.address:type_name -> arke.Address
	14, // 4: arke.Message.error:type_name -> arke.Error
	14, // 5: arke.MessageResponse.error:type_name -> arke.Error
	0,  // 6: arke.Address.type:type_name -> arke.Address.TargetType
	9,  // 7: arke.Address.parent_address:type_name -> arke.Address
	9,  // 8: arke.Source.address:type_name -> arke.Address
	27, // 9: arke.Source.options:type_name -> arke.Source.OptionsEntry
	11, // 10: arke.Source.filters:type_name -> arke.Filter
	1,  // 11: arke.Source.type:type_name -> arke.Source.TargetType
	12, // 12: arke.Filter.matches:type_name -> arke.Match
	2,  // 13: arke.Filter.type:type_name -> arke.Filter.MatchType
	14, // 14: arke.MessageConsumedResponse.error:type_name -> arke.Error
	10, // 15: arke.Consume.src:type_name -> arke.Source
	15, // 16: arke.Consume.ack:type_name -> arke.MessageConsumed
	14, // 17: arke.DeclareOnlyResponse.error:type_name -> arke.Error
	7,  // 18: arke.ConsumeResponse.msg:type_name -> arke.Message
	16, // 19: arke.ConsumeResponse.consumed_response:type_name -> arke.MessageConsumedResponse
	14, // 20: arke.ConsumeResponse.error:type_name -> arke.Error
	18, // 21: arke.ConsumeResponse.declare_only_response:type_name -> arke.DeclareOnlyResponse
	14, // 22: arke.SourceStats.error:type_name -> arke.Error
	10, // 23: arke.Sources.sources:type_name -> arke.Source
	14, // 24: arke.SourceStatsCollection.error:type_name -> arke.Error
	20, // 25: arke.SourceStatsCollection.stats:type_name -> arke.SourceStats
	28, // 26: arke.HealthStatus.time:type_name -> google.protobuf.Timestamp
	3,  // 27: arke.HealthStatus.code:type_name -> arke.HealthStatus.Code
	23, // 28: arke.Health.check:type_name -> arke.HealthCheck
	24, // 29: arke.Health.status:type_name -> arke.HealthStatus
	4,  // 30: arke.Producer.Connect:input_type -> arke.ConnectionConfiguration
	7,  // 31: arke.Producer.Publish:input_type -> arke.Message
	7,  // 32: arke.Producer.PublishOne:input_type -> arke.Message
	13, // 33: arke.Producer.Disconnect:input_type -> arke.Empty
	4,  // 34: arke.Consumer.Connect:input_type -> arke.ConnectionConfiguration
	17, // 35: arke.Consumer.Consume:input_type -> arke.Consume
	13, // 36: arke.Consumer.Disconnect:input_type -> arke.Empty
	10, // 37: arke.Consumer.SourceStats:input_type -> arke.Source
	21, // 38: arke.Consumer.SourceStatsGroup:input_type -> arke.Sources
	25, // 39: arke.Healthz.Check:input_type -> arke.Health
	6,  // 40: arke.Producer.Connect:output_type -> arke.ConnectResponse
	8,  // 41: arke.Producer.Publish:output_type -> arke.MessageResponse
	8,  // 42: arke.Producer.PublishOne:output_type -> arke.MessageResponse
	13, // 43: arke.Producer.Disconnect:output_type -> arke.Empty
	6,  // 44: arke.Consumer.Connect:output_type -> arke.ConnectResponse
	19, // 45: arke.Consumer.Consume:output_type -> arke.ConsumeResponse
	13, // 46: arke.Consumer.Disconnect:output_type -> arke.Empty
	20, // 47: arke.Consumer.SourceStats:output_type -> arke.SourceStats
	22, // 48: arke.Consumer.SourceStatsGroup:output_type -> arke.SourceStatsCollection
	25, // 49: arke.Healthz.Check:output_type -> arke.Health
	40, // [40:50] is the sub-list for method output_type
	30, // [30:40] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_arke_proto_init() }
func file_arke_proto_init() {
	if File_arke_proto != nil {
		return
	}
	file_arke_proto_msgTypes[13].OneofWrappers = []any{
		(*Consume_Src)(nil),
		(*Consume_Ack)(nil),
	}
	file_arke_proto_msgTypes[15].OneofWrappers = []any{
		(*ConsumeResponse_Msg)(nil),
		(*ConsumeResponse_ConsumedResponse)(nil),
		(*ConsumeResponse_Error)(nil),
		(*ConsumeResponse_DeclareOnlyResponse)(nil),
	}
	file_arke_proto_msgTypes[21].OneofWrappers = []any{
		(*Health_Check)(nil),
		(*Health_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arke_proto_rawDesc), len(file_arke_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_arke_proto_goTypes,
		DependencyIndexes: file_arke_proto_depIdxs,
		EnumInfos:         file_arke_proto_enumTypes,
		MessageInfos:      file_arke_proto_msgTypes,
	}.Build()
	File_arke_proto = out.File
	file_arke_proto_goTypes = nil
	file_arke_proto_depIdxs = nil
}
